### ISSUE TITLE
Text-drop down displaying underscores in output deliverables

### ISSUE THREAD

**Issue by RRouth** [ChrisZieba/LogicPull#26]
We have an issue that is becoming quite problematic with text drop-down fields in LogicPull. Specifically, when we select a value from a drop-down field that contains a space or a special character, like a dash, it replaces it with an underscore in all of the deliverables.

As you can see in the attachment screenshot, the value we are talking about is actually taken from the ID. Would this be a difficult issue to fix? Thanks.

**Comment by ChrisZieba** [comment]
In the stylesheet you can select the text of the dropdown item instead of the id using this code:

```
<%= master['q0_0'].values.label[master['q0_0'].getAnswer()] %>
```

**Comment by ChrisZieba** [comment]
The `fieldLabel` method was also reimplemented to be faster. It can be used in interviews to output the label of a field:

```
<%fieldLabel('q0_0', q0_0)%>
```
