### ISSUE TITLE
demo is not loading

### ISSUE THREAD

**Issue by leonhatori** [ChrisZieba/LogicPull#31]
I am trying to load the tool on brave browser. 
Is it compatible?

**Comment by ChrisZieba** [comment]
It should work. What do you mean it's not loading? Can you provide your config file, the url you're trying to load, what the error message is, etc.

**Comment by leonhatori** [comment]
its the demo of the logic pull.

**Comment by leonhatori** [comment]
this one: http://demo.logicpull.com/interviews/active/3

**Comment by rhd** [comment]
ditto, not loading for me either - the icon just spins and spins. I'm using chrome on LInux.

**Comment by leonhatori** [comment]
working now. don't know if there was any changes to the demo
